apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-server
  annotations:
    workflows.nholuongut.io/rbac-rule: "'authors' in groups && email == 'kilgore@kilgore.trout'"
    workflows.nholuongut.io/rbac-rule-precedence: "1"
