apiVersion: nholuongut.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-parameters-from-configmap-
  labels:
    workflows.nholuongut.io/test: "true"
  annotations:
    workflows.nholuongut.io/description: |
      This example demonstrates loading parameter values from configmap.
      Note that the "simple-parameters" ConfigMap (defined in examples/configmaps/simple-parameters-configmap.yaml)
      needs to be created first before submitting this workflow.
    workflows.nholuongut.io/verify.py: |
      assert status["phase"] == "Succeeded"
spec:
  serviceAccountName: argo
  entrypoint: whalesay

  templates:
  - name: whalesay
    inputs:
      parameters:
      # Parameters can also be passed via configmap reference.
      - name: message
        valueFrom:
          configMapKeyRef:
            name: simple-parameters
            key: msg
    container:
      image: nholuongut/argosay:v2
      args: ["echo", "{{inputs.parameters.message}}"]
