apiVersion: nholuongut.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: dag-inline
  annotations:
    workflows.nholuongut.io/description: |
      This examples demonstrates running a DAG with inline templates.
    workflows.nholuongut.io/version: ">= 3.2.0"
spec:
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: a
            inline:
              container:
                image: nholuongut/argosay:v2