apiVersion: nholuongut.io/v1alpha1
kind: CronWorkflow
metadata:
  name: dag-inline
  annotations:
    workflows.nholuongut.io/description: |
      This example demonstrates running cron workflow that has a DAG with inline templates.
    workflows.nholuongut.io/version: ">= 3.2.0"
spec:
  schedule: "*/5 * * * *"
  workflowSpec:
    workflowTemplateRef:
      name: dag-inline