apiVersion: nholuongut.io/v1alpha1
kind: Workflow
metadata:
  generateName: global-parameter-values-from-configmap-
  labels:
    workflows.nholuongut.io/test: "true"
  annotations:
    workflows.nholuongut.io/description: |
      This example demonstrates loading global parameter values from configmap.
      Note that the "simple-parameters" ConfigMap (defined in examples/configmaps/simple-parameters-configmap.yaml)
      needs to be created first before submitting this workflow.
spec:
  serviceAccountName: argo
  entrypoint: whalesay
  # Parameters can also be passed via configmap reference.
  arguments:
    parameters:
    - name: message
      valueFrom:
        configMapKeyRef:
          name: simple-parameters
          key: msg

  templates:
  - name: whalesay
    container:
      image: nholuongut/argosay:v2
      args: ["echo", "{{workflow.parameters.message}}"]
