apiVersion: nholuongut.io/v1alpha1
kind: Workflow
metadata:
  generateName: selected-executor-
  labels:
    # run this workflow as a part of our test suite
    workflows.nholuongut.io/test: "true"
    # use the pns executor, rather than the default (typically emissary)
    workflows.nholuongut.io/container-runtime-executor: pns
  annotations:
    workflows.nholuongut.io/description: |

      This workflow demonstrates using an annotation to run a the pod using a different executor to the default
      configured executor.

      In this example, it uses a label that state the executor to use explictly, but you can also do this indirectly,
      e.g. have a certain labels use certain executors.

    # this workflow will only run on workflows version v3.0.0
    workflows.nholuongut.io/version: ">= 3.0.0"
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: nholuongut/argosay:v2