apiVersion: nholuongut.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-inline-
  labels:
    workflows.nholuongut.io/test: "true"
  annotations:
    workflows.nholuongut.io/description: |
      This workflow demonstrates running a steps with inline templates.
    workflows.nholuongut.io/version: ">= 3.2.0"
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: a
            inline:
              container:
                image: nholuongut/argosay:v2